"""add Department

Revision ID: 503e4f0e6c8b
Revises: dbcb6e7a007b
Create Date: 2024-10-01 23:44:04.990652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503e4f0e6c8b'
down_revision = 'dbcb6e7a007b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
