"""rename department

Revision ID: ee4ea8d0b1e0
Revises: 503e4f0e6c8b
Create Date: 2024-10-01 23:56:01.651361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4ea8d0b1e0'
down_revision = '503e4f0e6c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###